### PR TITLE
Fix yaml conversion of post addresses

### LINKED ISSUE #323: only one address shown when editing a contact with multiple {home,work} addresses
i can save a contact with multiple home addresses.
using `khard show first last` i see the following:

```
Name: first last
Full name: first last
Address book: contacts
Kind: individual
Phone
    cell:
        - 123
        - 456
        - 789
E-Mail
    home:
        - 01@home.tld
        - 02@home.tld
        - 03@home.tld
Address
    home:
        -
            street 1
            00001 city01
            country01
        -
            street 2
            00002 city02
            country02
        -
            street 3
            00003 city03
            country03
Miscellaneous
    UID: 3vijrweg08clpmpf8hoobu2pelizf8xxo6pl
```

when i edit the contact using `khard edit first last`, i am only shown one of the addresses:

```
Phone:
    cell:
      - '123'
      - '456'
      - '789'

# email addresses
# format like phone numbers above
# allowed types:
#   vcard 3.0: At least one of home, internet, pref, work, x400
#   vcard 4.0: At least one of home, internet, pref, work
#   Alternatively you may use a single custom label (only letters).
Email:
    home:
      - 01@home.tld
      - 02@home.tld
      - 03@home.tld

# post addresses
# allowed types:
#   vcard 3.0: At least one of dom, intl, home, parcel, postal, pref, work
#   vcard 4.0: At least one of home, pref, work
#   Alternatively you may use a single custom label (only letters).
Address:
    home:
        Box:
        Extended:
        Street: street 1
        Code: '00001'
        City: city01
        Region:
        Country: country01
```

when editing the vcard using `khard edit --format vcard first last`, everything seems to be in order:

```
BEGIN:VCARD
VERSION:4.0
UID:3vijrweg08clpmpf8hoobu2pelizf8xxo6pl
ADR;TYPE=home:;;street 1;city01;;00001;country01
ADR;TYPE=home:;;street 2;city02;;00002;country02
ADR;TYPE=home:;;street 3;city03;;00003;country03
EMAIL;TYPE=home:01@home.tld
EMAIL;TYPE=home:02@home.tld
EMAIL;TYPE=home:03@home.tld
FN:first last
N:last;first;;;
REV:20230906T075413Z
TEL;TYPE=cell;VALUE=uri:tel:123
TEL;TYPE=cell;VALUE=uri:tel:456
TEL;TYPE=cell;VALUE=uri:tel:789
END:VCARD
```

the same applies for multiple other addresses. only every one of the multiples is shown in the .yaml file.

i think this used to work as expected. unfortunately i'm not sure when this stopped working for me. is this a setting of mine or a bug?

hope i didn't miss a duplicate of this issue.

`Khard version 0.18.0`

### PR DESCRIPTION
**Pull request by lucc**
This fixes #323.

### CODE REVIEW

**Comment by lucc** [comment]
@lemmerk can you confirm that this fixes your issue?

@skowalak   do you know why you only returned the first address with  9ab66ac? 
It looks the original code handles lists of addresses under one label:

https://github.com/lucc/khard/commit/9ab66ac0dab45da8665afa2033950946162f299d#diff-a189618efcc4fcc11fb726bee1742df072e671aace70782e53e4b2b8c1074f70L1316-L1320

But the new code only picks the first list:

https://github.com/lucc/khard/commit/9ab66ac0dab45da8665afa2033950946162f299d#diff-66dd891e1f121132ebda2ced9353326dc336e5a396c6f95511a4487d6df5f61cR124-R125

I could not find any discussion about this in #302 even though I made an unrelated comment about this piece of code https://github.com/lucc/khard/pull/302#discussion_r815494364
I must have missed this issue back then.

**Comment by lemmerk** [comment]
not sure how to check. followed the instructions in the [dev](https://github.com/lucc/khard/blob/develop/CONTRIBUTING.rst#development) section (i think) but it wouldn't run due to a missing version.py.
`ModuleNotFoundError: No module named 'khard.version'`

**Comment by skowalak** [comment]
@lucc You are right, my code apparently only picks the first address in the list. I cannot remember why this was introduced by me, thank you for fixing it!

**Comment by lucc** [comment]
@lemmerk I suggest you enter a venv and then install with pip.  I have to rewrite these notes some time but currently I am using nix flakes.

**Pull request merged**
